language: python
python:
  - 2.6
  - 2.7
  - pypy
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -q -e . --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E272,E221,E241 usersettings"
  -  '[ "$TRAVIS_PYTHON_VERSION" \> 3 ] || pyflakes -x W usersettings'
script:
  - python example_project/manage.py test
